# Generated by Django 4.2.15 on 2024-11-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mathquiz", "0004_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
