# Generated by Django 4.2.15 on 2024-12-02 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mathquiz", "0009_student_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="user",),
    ]
