# Generated by Django 4.2.15 on 2024-12-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mathquiz", "0011_student_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="user",),
    ]
